### PR TITLE
Fixes profile page errors on staging

### LINKED ISSUE #2007: Members#show error when planting had planted_at=nil

### PR DESCRIPTION
**Pull request by Br3nda**
closes #2007 

fixes members#show error when planted_at is nil

and add lots of specs

### CODE REVIEW

File: spec/features/members/profile_spec.rb [hunk 1]
```diff
@@ -52,18 +48,6 @@
       end
     end
 
-    context "email privacy" do
```
Comment (Br3nda) [inline spec/features/members/profile_spec.rb]: this whole segment was in the file twice

**Comment by pozorvlak** [comment]
approve

**Comment by pozorvlak** [comment]
Also, Percy thinks I'm not a member of the organisation, so I can't approve the design changes.
