### PR TITLE
Fix crash on adding Flickr photo

### LINKED ISSUE #3691: Adding Photos to a Plant Results in a 500
While trying to add a photo to my plant, I was confronted with a 500-server error. I could successfully connect to Flickr and see my picture, but when I select it, I get the error. 

| Image Connected via Flickr | 500 Error |
|----------------|--------------|
|Screenshot 2024-03-25 at 20 53 21|Screenshot 2024-03-25 at 20 53 27|

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix #3691 ?

https://www.flickr.com/services/api/flickr.photos.licenses.getInfo.htm

### CODE REVIEW

File: app/models/photo.rb [hunk 1]
```diff
@@ -47,6 +47,7 @@ def flickr_metadata
     info = flickr.photos.getInfo(photo_id: source_id)
     licenses = flickr.photos.licenses.getInfo
     license = licenses.find { |l| l.id == info.license }
+    Rails.logger.error("Cannot find license: " + [info.license, licences].inspect) unless license
```
Comment (CloCkWeRX) [inline app/models/photo.rb]:
```suggestion
    Rails.logger.error("Cannot find license: " + [info.license, licenses].inspect) unless license
```

File: app/models/photo.rb [hunk 2]
```diff
@@ -47,6 +47,7 @@ def flickr_metadata
     info = flickr.photos.getInfo(photo_id: source_id)
     licenses = flickr.photos.licenses.getInfo
     license = licenses.find { |l| l.id == info.license }
```
Comment (CloCkWeRX) [inline app/models/photo.rb]:
```suggestion
    license = licenses.find { |l| l.id.to_i == info.license.to_i }
```
